### ISSUE TITLE
Description, year and rating mixed in GameDBInfo of Sega MegaDrive

### ISSUE THREAD

**Issue by h3llrais3r** [Wintermute0110/plugin.program.AEL#46] opened 2017-11-04 18:51 UTC
Apparently description, year and rating have been mislabeled (wrong tag) in the GameDBInfo of Sega MegaDrive.
See https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/blob/master/GameDBInfo/Sega%20MegaDrive.xml

Example:
https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/blob/master/GameDBInfo/Sega%20MegaDrive.xml#L10-L12

This causes the year to show up in kodi instead of the description.

**Comment by Wintermute0110** [comment] 2017-11-06 07:33
Thanks for reporting. Offline scraper will be fixed in 0.9.8. It's a huge task and will take some time, though.

**Comment by h3llrais3r** [comment] 2017-11-06 14:40
I think this could be easily done with some xslt transformation 😉

**Comment by h3llrais3r** [comment] 2017-11-06 21:55
@Wintermute0110 Please find in attachment a fixed version of the "Sega Megadrive.xml".
I've changed it by applying some xslt transformations. Feel free to check it out and use it if it suits your needs. 😉  It's not in the exact layout (empty elements are in short notation <crc/> instead of <crc></crc>) so you'll probably want to do some modifications.

**Comment by Wintermute0110** [comment] 2017-11-07 08:06
Thanks a lot for your help.

Yeah, changing *one* XML is easy. What is a huge task is to fix **all** the XMLs.

Have a look (at this repo)[https://github.com/Wintermute0110/AEL-offline-scraper]. The original files of the offline scraper are CSV files made by Billyc666 and the problem is that some of the CSV files are wrong. Currently, `convert_GameDBInfo_CVS_to_XML.py` converts the CSV files to XML and that Python file is the one that needs a fix.

For 0.9.8, I plan to combine the XML output files produced by `convert_GameDBInfo_CVS_to_XML.py` with a No-Intro or Redump DAT file to produce the final offline scraper XML. Once the CSV to XML conversion is fixed I will abandon the CSV files forever and keep using the XML only. Users will be able to edit the XML to improve the Offline Scraper database.

Still there are some things I have to think about like Parent/Clone generation. 0.9.8 is going to take some time to develop and I will be somewhat busy with real life in the next months. I would say a realistic release time for 0.9.8 could be February or March 2018.

**Comment by h3llrais3r** [comment] 2017-11-07 18:29
I just ran the converter for csv to xml and the data for Sega MegaDrive is correct (Description, year and rating is correct). The xml for Sega MegaDrive in your plugin is not the same as the output generated by the converter... is this normal?

**Comment by h3llrais3r** [comment] 2017-11-07 19:28
Made 2 PR's that may already help you:
https://github.com/Wintermute0110/Game-database-info/pull/3
https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/pull/50

When generating the xml's from csv's with these changes, a lot of errors are fixed.

**Comment by Wintermute0110** [comment] 2017-11-08 08:29
> I just ran the converter for csv to xml and the data for Sega MegaDrive is correct (Description, year and rating is correct). The xml for Sega MegaDrive in your plugin is not the same as the output generated by the converter... is this normal?

AEL-offline-repo is still in design state. Also, I have some uncommited files in one of my computers. As soon as I have some time I will update that repo.

**Comment by h3llrais3r** [comment] 2017-11-24 18:19
@Wintermute0110 You didn't regenerate the gamedbinfo xml files for release 0.9.7?
Sega MegaDrive still has wrong xml tags.

**Comment by Wintermute0110** [comment] 2017-11-25 12:48
No, I didn't touch the scrapers in 0.9.7. 0.9.8 will be the "scrapers edition" and I plan to polish the scrapers a lot, also finally adding the (Levenshtein distance algortihm)[https://en.wikipedia.org/wiki/Levenshtein_distance]. Unfortunately, my free time during Christmas sessions is going to be very limited.

OK, no problem at all updating the submodules in `AEL-offline-scraper`. I have already done it for you.

**Comment by h3llrais3r** [comment] 2017-11-25 17:14
Thanks. No need to rush. My time is also limited, and it's not that this is really urgent. 😉

**Comment by Wintermute0110** [comment] 2021-06-08 07:08
This was fixed some time ago so I'm closing this issue. There are still some problems with the offline scraper, I will solve those when I had time.

**Closed by Wintermute0110** 2021-06-08 07:08 UTC
Labels: Scrapers, bug
