### ISSUE TITLE
Can't add ROMs to Collection

### ISSUE THREAD

**Issue by bjornbrandy** [Wintermute0110/plugin.program.AEL#57] opened 2017-12-29 13:16 UTC
Hi,

WIN10 64bit
KODI from win store 17.6

When I want to add an ROM to collection I get an error. I press "C" on a ROM then select "Add ROM to Collection" and after that error.

I thin k this is the right part, but I alos attached the LOG file.

15:05:26.630 T:1648   ERROR: AEL ERROR: SingleInstance::__exit__() Unhandled excepcion in protected code
15:05:26.635 T:1648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'launcherID'
                                            Traceback (most recent call last):
                                              File "C:\Users\brand\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 39, in <module>
                                                main.Main().run_plugin()
                                              File "C:\Users\brand\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 289, in run_plugin
                                                self.run_protected(command, args)
                                              File "C:\Users\brand\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 396, in run_protected
                                                self._command_add_ROM_to_collection(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "C:\Users\brand\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 5561, in _command_add_ROM_to_collection
                                                virtualLauncherID = rom['launcherID']
                                            KeyError: u'launcherID'
                                            -->End of Python script error report<--
[kodi.log](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/files/1593139/kodi.log)

**Comment by Wintermute0110** [comment] 2018-01-16 08:13
Thanks a lot for reporting. I have tried adding ROMs to a Collection from a regular launcher and I cannot reproduce the bug. Does the problem happen in a standard ROM Launcher, Favourites or a Virtual Launcher (for example, "Browse ROMs by Title", "Browse by Year", etc.?

**Comment by Wintermute0110** [comment] 2019-12-09 07:04
I cannot reproduce this bug and I didn't get any more comments from OP so I'm closing the issue.

**Closed by Wintermute0110** 2019-12-09 07:04 UTC
